# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

# Copyright (c) 2025 OmniNode Team
"""Registration Confirmation Model for Dual Registration Workflow.  # ai-slop-ok: pre-existing docstring opener

This module provides ModelRegistrationConfirmation, the Pydantic model for
confirmation events from the Effect layer. These events complete the
registration workflow by confirming PostgreSQL operations.

Implementation Status:
    This model is actively used in production by
    RegistrationReducer.reduce_confirmation() (OMN-996).

    - Effect layer nodes (PostgresAdapter) publish confirmation events using
      this model
    - RegistrationReducer.reduce_confirmation() processes these events
    - Runtime routes confirmations based on event_type

Confirmation Event Flow:
    1. Reducer emits intents (postgres.upsert_registration)
    2. Effect nodes execute intents and perform I/O
    3. Effect nodes publish confirmation events to Kafka
    4. Runtime routes confirmations to RegistrationReducer.reduce_confirmation()
    5. Reducer updates state: pending -> complete (or -> failed)

Event Types:

    - postgres.registration_upserted: PostgreSQL record upsert completed

    This event type may indicate success or failure via the ``success`` field.
    On failure, ``error_message`` provides diagnostic information (sanitized).

State Transitions Triggered:
    - success + postgres.registration_upserted:
        pending -> complete

    - failure (any event_type):
        pending -> failed

Related:
    - RegistrationReducer: Pure reducer that consumes this model
    - ModelRegistrationState: State model updated by confirmations
    - DESIGN_TWO_WAY_REGISTRATION_ARCHITECTURE.md: Architecture design
    - OMN-889: Infrastructure MVP - Dual Registration Reducer
    - OMN-996: Implement Confirmation Event Handling (follow-up)
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, model_validator

from omnibase_infra.enums import EnumConfirmationEventType


class ModelRegistrationConfirmation(BaseModel):
    """Confirmation event for registration operations.

    This model represents confirmation events published by the PostgreSQL
    Effect layer node (PostgresAdapter) after executing registration intents.

    Usage:
        This model is consumed by RegistrationReducer.reduce_confirmation()
        to transition registration state through the confirmation workflow.

    Immutability:
        This model uses frozen=True to ensure confirmation events are immutable
        once created. This aligns with the immutable event sourcing pattern.

    Serialization:
        This model is designed for Kafka transport. Effect nodes serialize using
        ``model_dump(mode="json")`` and the Runtime deserializes using
        ``model_validate()``.

    Security Note:
        The ``error_message`` field should contain sanitized error information
        only. Effect nodes must NOT include credentials, connection strings,
        or other sensitive information in error messages. See CLAUDE.md
        "Error Sanitization Guidelines" for details.

    Attributes:
        event_type: The type of confirmation event.
            - "postgres.registration_upserted": PostgreSQL upsert result
        correlation_id: UUID linking this confirmation to the original
            introspection event. Used by the reducer to match confirmations
            to pending registrations.
        node_id: UUID of the node being registered. Used for validation
            to ensure confirmation matches the expected node.
        success: Whether the registration operation succeeded.
            - True: Operation completed successfully
            - False: Operation failed (see error_message)
        error_message: Optional error message if success is False.
            Must be sanitized - no credentials or PII.
        timestamp: When the confirmation was generated by the Effect node.
            Used for observability and timeout tracking.

    Example:
        >>> from datetime import datetime, UTC
        >>> from uuid import uuid4
        >>> from omnibase_infra.enums import EnumConfirmationEventType
        >>> confirmation = ModelRegistrationConfirmation(
        ...     event_type=EnumConfirmationEventType.POSTGRES_REGISTRATION_UPSERTED,
        ...     correlation_id=uuid4(),
        ...     node_id=uuid4(),
        ...     success=True,
        ...     timestamp=datetime.now(UTC),
        ... )
        >>> confirmation.event_type
        <EnumConfirmationEventType.POSTGRES_REGISTRATION_UPSERTED: 'postgres.registration_upserted'>
        >>> confirmation.success
        True

    Example (failure case):
        >>> from omnibase_infra.enums import EnumConfirmationEventType
        >>> confirmation = ModelRegistrationConfirmation(
        ...     event_type=EnumConfirmationEventType.POSTGRES_REGISTRATION_UPSERTED,
        ...     correlation_id=uuid4(),
        ...     node_id=uuid4(),
        ...     success=False,
        ...     error_message="Connection refused to database host",
        ...     timestamp=datetime.now(UTC),
        ... )
        >>> confirmation.success
        False
        >>> confirmation.error_message
        'Connection refused to database host'
    """

    model_config = ConfigDict(frozen=True, extra="forbid", from_attributes=True)

    event_type: EnumConfirmationEventType = Field(
        ...,
        description="The type of confirmation event (postgres)",
    )
    correlation_id: UUID = Field(
        ...,
        description="UUID linking this to the original registration request",
    )
    node_id: UUID = Field(
        ...,
        description="UUID of the node being registered",
    )
    success: bool = Field(
        ...,
        description="Whether the registration operation succeeded",
    )
    error_message: str | None = Field(
        default=None,
        description="Optional sanitized error message if success is False",
    )
    timestamp: datetime = Field(
        ...,
        description="When the confirmation was generated",
    )

    @model_validator(mode="after")
    def _validate_error_message_consistency(self) -> ModelRegistrationConfirmation:
        """Enforce that error_message is only set when success is False.

        Invariant:
            - success=True requires error_message=None
            - success=False may optionally include an error_message
        """
        if self.success and self.error_message is not None:
            msg = (
                "error_message must be None when success is True, "
                f"got error_message={self.error_message!r}"
            )
            raise ValueError(msg)
        return self


__all__ = ["ModelRegistrationConfirmation"]
