# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Tests for scripts/validation/check_topic_completeness.py (OMN-3257)."""

from __future__ import annotations

import textwrap
from pathlib import Path

import pytest

from scripts.validation.check_topic_completeness import (
    check_completeness,
    collect_registry_from_constants_file,
    collect_registry_from_contracts,
    load_allowlist,
    main,
    scan_source_for_topics,
)


@pytest.mark.unit
class TestCollectRegistryFromContracts:
    """Tests for contract YAML topic extraction."""

    def test_extracts_subscribe_topics(self, tmp_path: Path) -> None:
        contract = tmp_path / "node_a" / "contract.yaml"
        contract.parent.mkdir()
        contract.write_text(
            textwrap.dedent("""\
            name: node_a
            event_bus:
              subscribe_topics:
                - onex.evt.platform.node-registration.v1
                - topic: onex.cmd.platform.request-introspection.v1
              publish_topics:
                - onex.evt.platform.node-heartbeat.v1
            """)
        )
        topics = collect_registry_from_contracts(tmp_path)
        assert "onex.evt.platform.node-registration.v1" in topics
        assert "onex.cmd.platform.request-introspection.v1" in topics
        assert "onex.evt.platform.node-heartbeat.v1" in topics

    def test_extracts_consumed_published_events(self, tmp_path: Path) -> None:
        contract = tmp_path / "node_b" / "contract.yaml"
        contract.parent.mkdir()
        contract.write_text(
            textwrap.dedent("""\
            name: node_b
            consumed_events:
              - topic: onex.evt.omniclaude.session-outcome.v1
                name: onex.cmd.omniintelligence.session-outcome.v1
            published_events:
              - topic: onex.evt.platform.node-introspection.v1
            """)
        )
        topics = collect_registry_from_contracts(tmp_path)
        assert "onex.evt.omniclaude.session-outcome.v1" in topics
        assert "onex.cmd.omniintelligence.session-outcome.v1" in topics
        assert "onex.evt.platform.node-introspection.v1" in topics

    def test_nonexistent_root_returns_empty(self, tmp_path: Path) -> None:
        topics = collect_registry_from_contracts(tmp_path / "nonexistent")
        assert topics == set()

    def test_empty_contract_returns_empty(self, tmp_path: Path) -> None:
        contract = tmp_path / "contract.yaml"
        contract.write_text("name: empty_node\n")
        topics = collect_registry_from_contracts(tmp_path)
        assert topics == set()


@pytest.mark.unit
class TestCollectRegistryFromConstantsFile:
    """Tests for Python constants file topic extraction."""

    def test_extracts_topic_constants(self, tmp_path: Path) -> None:
        constants = tmp_path / "topic_constants.py"
        constants.write_text(
            textwrap.dedent("""\
            TOPIC_A = "onex.evt.platform.node-registration.v1"
            TOPIC_B = "onex.cmd.omniclaude.session-outcome.v1"
            NOT_A_TOPIC = "some.other.string"
            """)
        )
        topics = collect_registry_from_constants_file(constants)
        assert "onex.evt.platform.node-registration.v1" in topics
        assert "onex.cmd.omniclaude.session-outcome.v1" in topics
        assert "some.other.string" not in topics

    def test_nonexistent_file_returns_empty(self, tmp_path: Path) -> None:
        topics = collect_registry_from_constants_file(tmp_path / "nope.py")
        assert topics == set()


@pytest.mark.unit
class TestScanSourceForTopics:
    """Tests for Python source scanning."""

    def test_finds_topic_literals(self, tmp_path: Path) -> None:
        src = tmp_path / "module.py"
        src.write_text(
            textwrap.dedent("""\
            TOPIC = "onex.evt.platform.node-registration.v1"
            other = "not a topic"
            another = "onex.cmd.omniclaude.test-thing.v1"
            """)
        )
        results = scan_source_for_topics(tmp_path)
        topics = {t for _, t, _ in results}
        assert "onex.evt.platform.node-registration.v1" in topics
        assert "onex.cmd.omniclaude.test-thing.v1" in topics
        assert "not a topic" not in topics

    def test_excludes_tests_directory(self, tmp_path: Path) -> None:
        tests_dir = tmp_path / "tests"
        tests_dir.mkdir()
        src = tests_dir / "test_foo.py"
        src.write_text('TOPIC = "onex.evt.platform.node-registration.v1"\n')
        results = scan_source_for_topics(tmp_path)
        assert len(results) == 0

    def test_excludes_generated_files(self, tmp_path: Path) -> None:
        src = tmp_path / "generated_enum.py"
        src.write_text(
            textwrap.dedent("""\
            # GENERATED by codegen tool
            TOPIC = "onex.evt.platform.node-registration.v1"
            """)
        )
        results = scan_source_for_topics(tmp_path)
        assert len(results) == 0

    def test_handles_syntax_errors(self, tmp_path: Path) -> None:
        src = tmp_path / "bad.py"
        src.write_text("def foo(\n")  # syntax error
        results = scan_source_for_topics(tmp_path)
        assert len(results) == 0


@pytest.mark.unit
class TestLoadAllowlist:
    """Tests for allowlist loading."""

    def test_loads_yaml_format(self, tmp_path: Path) -> None:
        allowlist = tmp_path / "allowlist.yaml"
        allowlist.write_text(
            textwrap.dedent("""\
            allowlist:
              - onex.evt.platform.test-topic.v1
              - onex.cmd.omniclaude.other-topic.v1
            """)
        )
        topics = load_allowlist(allowlist)
        assert "onex.evt.platform.test-topic.v1" in topics
        assert "onex.cmd.omniclaude.other-topic.v1" in topics

    def test_loads_plain_text_format(self, tmp_path: Path) -> None:
        allowlist = tmp_path / "allowlist.txt"
        allowlist.write_text(
            textwrap.dedent("""\
            # Comment line
            onex.evt.platform.test-topic.v1
            onex.cmd.omniclaude.other-topic.v1
            """)
        )
        topics = load_allowlist(allowlist)
        assert "onex.evt.platform.test-topic.v1" in topics
        assert "onex.cmd.omniclaude.other-topic.v1" in topics

    def test_nonexistent_file_returns_empty(self, tmp_path: Path) -> None:
        topics = load_allowlist(tmp_path / "nope.yaml")
        assert topics == set()


@pytest.mark.unit
class TestCheckCompleteness:
    """Integration tests for the check_completeness function."""

    def test_registered_topic_passes(self, tmp_path: Path) -> None:
        # Create a constants file with the topic
        constants = tmp_path / "topics.py"
        constants.write_text('TOPIC = "onex.evt.platform.node-registration.v1"\n')

        # Create source that references the same topic
        src = tmp_path / "module.py"
        src.write_text('MY_TOPIC = "onex.evt.platform.node-registration.v1"\n')

        unregistered, registry = check_completeness(src_root=tmp_path)
        assert len(unregistered) == 0
        assert "onex.evt.platform.node-registration.v1" in registry

    def test_unregistered_topic_fails(self, tmp_path: Path) -> None:
        # Source with a topic that is NOT in any registry
        src = tmp_path / "module.py"
        src.write_text('MY_TOPIC = "onex.evt.fake.unknown-topic.v1"\n')

        unregistered, _ = check_completeness(src_root=tmp_path)
        assert len(unregistered) == 1
        assert unregistered[0][1] == "onex.evt.fake.unknown-topic.v1"

    def test_allowlisted_topic_passes(self, tmp_path: Path) -> None:
        # Source with a topic that is NOT in registry but IS in allowlist
        src = tmp_path / "module.py"
        src.write_text('MY_TOPIC = "onex.evt.fake.allowed-topic.v1"\n')

        allowlist = tmp_path / "allowlist.yaml"
        allowlist.write_text("allowlist:\n  - onex.evt.fake.allowed-topic.v1\n")

        unregistered, _ = check_completeness(
            src_root=tmp_path, allowlist_path=allowlist
        )
        assert len(unregistered) == 0

    def test_contract_registered_topic_passes(self, tmp_path: Path) -> None:
        # Create contract with topic
        contracts = tmp_path / "contracts"
        contracts.mkdir()
        contract = contracts / "contract.yaml"
        contract.write_text(
            textwrap.dedent("""\
            name: test_node
            event_bus:
              subscribe_topics:
                - onex.evt.platform.test-event.v1
            """)
        )

        # Create source referencing the same topic
        src = tmp_path / "src"
        src.mkdir()
        module = src / "module.py"
        module.write_text('TOPIC = "onex.evt.platform.test-event.v1"\n')

        unregistered, registry = check_completeness(
            src_root=src, contracts_root=contracts
        )
        assert len(unregistered) == 0
        assert "onex.evt.platform.test-event.v1" in registry


@pytest.mark.unit
class TestMainCLI:
    """Tests for the CLI entry point."""

    def test_clean_source_returns_zero(self, tmp_path: Path) -> None:
        # Create a registered topic
        topics_file = tmp_path / "topics.py"
        topics_file.write_text('T = "onex.evt.platform.node-registration.v1"\n')

        # Create source using the same topic
        module = tmp_path / "module.py"
        module.write_text('USE = "onex.evt.platform.node-registration.v1"\n')

        result = main(["--src", str(tmp_path), "--quiet"])
        assert result == 0

    def test_unregistered_returns_one(self, tmp_path: Path) -> None:
        module = tmp_path / "module.py"
        module.write_text('USE = "onex.evt.fake.unknown.v1"\n')

        result = main(["--src", str(tmp_path), "--quiet"])
        assert result == 1

    def test_show_registry(self, tmp_path: Path) -> None:
        topics_file = tmp_path / "topics.py"
        topics_file.write_text('T = "onex.evt.platform.test.v1"\n')

        result = main(["--src", str(tmp_path), "--show-registry"])
        assert result == 0

    def test_nonexistent_src_returns_two(self) -> None:
        result = main(["--src", "/nonexistent/path/to/src"])
        assert result == 2
