-- Migration: 013_add_run_id_to_pattern_injections
-- Description: Add run_id column to pattern_injections for pipeline measurement linkage
-- Author: omniintelligence
-- Date: 2026-02-11
-- Ticket: OMN-2133
--
-- Dependencies: 007_create_pattern_injections.sql (adds column to existing table)
-- Note: run_id is the canonical join key between session outcomes and pipeline
--       measurement runs. Generated by the orchestrator, persisted here.
--       NULL means no pipeline run is associated (OBSERVED-only attribution).

-- ============================================================================
-- Add run_id column
-- ============================================================================

ALTER TABLE pattern_injections
ADD COLUMN IF NOT EXISTS run_id UUID;

-- ============================================================================
-- Index for run_id lookups
-- ============================================================================

-- Partial index: only non-NULL run_ids for efficient join to pipeline runs
CREATE INDEX IF NOT EXISTS idx_pattern_injections_run_id
    ON pattern_injections(run_id)
    WHERE run_id IS NOT NULL;

-- ============================================================================
-- Comments
-- ============================================================================

COMMENT ON COLUMN pattern_injections.run_id IS 'Pipeline run ID linking injection to measurement data. NULL means no pipeline run (OBSERVED-only attribution). SD-2: canonical join key.';
