# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""ONEX Infrastructure Topic Constants.

Platform-reserved topic suffix constants for ONEX infrastructure components. Domain
services should NOT import from this module - domain topics should be defined in
domain contracts.

IMPORTANT: ONEX topics are realm-agnostic. Environment prefixes (dev., prod., etc.)
must NOT appear on the wire. Environment isolation is enforced via envelope identity
and consumer group naming, not topic prefixing. The canonical resolution path is
TopicResolver, which validates suffixes and returns them unchanged.

Exports:
    Platform topic suffix constants (e.g., SUFFIX_NODE_REGISTRATION)
    ALL_PLATFORM_SUFFIXES: Complete tuple of all platform-reserved suffixes
    TopicResolver: Canonical resolver for topic suffix -> concrete Kafka topic
    TopicResolutionError: Error raised when topic resolution fails
"""

from omnibase_infra.topics.model_bus_descriptor import ModelBusDescriptor
from omnibase_infra.topics.model_topic_spec import ModelTopicSpec
from omnibase_infra.topics.platform_topic_suffixes import (
    ALL_INTELLIGENCE_TOPIC_SPECS,
    ALL_OMNIBASE_INFRA_TOPIC_SPECS,
    ALL_OMNICLAUDE_TOPIC_SPECS,
    ALL_OMNIMEMORY_TOPIC_SPECS,
    ALL_PLATFORM_SUFFIXES,
    ALL_PLATFORM_TOPIC_SPECS,
    ALL_PROVISIONED_SUFFIXES,
    ALL_PROVISIONED_TOPIC_SPECS,
    ALL_VALIDATION_TOPIC_SPECS,
    SUFFIX_BASELINES_COMPUTED,
    SUFFIX_CIRCUIT_BREAKER_STATE,
    SUFFIX_CONSUMER_HEALTH,
    SUFFIX_CONSUMER_RESTART_CMD,
    SUFFIX_CONTRACT_DEREGISTERED,
    SUFFIX_CONTRACT_REGISTERED,
    SUFFIX_FEATURE_FLAG_CHANGED,
    SUFFIX_FSM_STATE_TRANSITIONS,
    SUFFIX_GMAIL_ARCHIVE_PURGED,
    SUFFIX_INTELLIGENCE_CLAUDE_HOOK_EVENT,
    SUFFIX_INTELLIGENCE_CODE_CRAWL_REQUESTED,
    SUFFIX_INTELLIGENCE_CODE_ENTITIES_EXTRACTED,
    SUFFIX_INTELLIGENCE_CODE_FILE_DISCOVERED,
    SUFFIX_INTELLIGENCE_DECISION_RECORDED_CMD,
    SUFFIX_INTELLIGENCE_DECISION_RECORDED_EVT,
    SUFFIX_INTELLIGENCE_INTENT_CLASSIFIED,
    SUFFIX_INTELLIGENCE_LLM_CALL_COMPLETED,
    SUFFIX_INTELLIGENCE_PATTERN_DISCOVERED,
    SUFFIX_INTELLIGENCE_PATTERN_LEARNED,
    SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITION,
    SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITIONED,
    SUFFIX_INTELLIGENCE_PATTERN_PROMOTED,
    SUFFIX_INTELLIGENCE_PATTERN_STORED,
    SUFFIX_INTELLIGENCE_SESSION_OUTCOME,
    SUFFIX_NODE_HEARTBEAT,
    SUFFIX_NODE_INTROSPECTION,
    SUFFIX_NODE_REGISTRATION,
    SUFFIX_NODE_REGISTRATION_ACCEPTED,
    SUFFIX_NODE_REGISTRATION_ACKED,
    SUFFIX_OMNICLAUDE_AGENT_ACTIONS,
    SUFFIX_OMNICLAUDE_AGENT_ACTIONS_DLQ,
    SUFFIX_OMNICLAUDE_AGENT_EXECUTION_LOGS,
    SUFFIX_OMNICLAUDE_AGENT_OBSERVABILITY_DLQ,
    SUFFIX_OMNICLAUDE_AGENT_STATUS,
    SUFFIX_OMNICLAUDE_AGENT_TRACE_FIX_TRANSITION,
    SUFFIX_OMNICLAUDE_AGENT_TRANSFORMATION,
    SUFFIX_OMNICLAUDE_AUDIT_COMPRESSION_TRIGGERED,
    SUFFIX_OMNICLAUDE_AUDIT_CONTEXT_BUDGET_EXCEEDED,
    SUFFIX_OMNICLAUDE_AUDIT_DISPATCH_VALIDATED,
    SUFFIX_OMNICLAUDE_AUDIT_RETURN_BOUNDED,
    SUFFIX_OMNICLAUDE_AUDIT_SCOPE_VIOLATION,
    SUFFIX_OMNICLAUDE_CONTEXT_AUDIT_DLQ,
    SUFFIX_OMNICLAUDE_DETECTION_FAILURE,
    SUFFIX_OMNICLAUDE_PERFORMANCE_METRICS,
    SUFFIX_OMNICLAUDE_ROUTING_DECISION,
    SUFFIX_OMNICLAUDE_SKILL_COMPLETED,
    SUFFIX_OMNICLAUDE_SKILL_LIFECYCLE_DLQ,
    SUFFIX_OMNICLAUDE_SKILL_STARTED,
    SUFFIX_OMNIINTELLIGENCE_ROUTING_DECISION_CMD,
    SUFFIX_OMNIMEMORY_ARCHIVE_MEMORY,
    SUFFIX_OMNIMEMORY_CRAWL_REQUESTED,
    SUFFIX_OMNIMEMORY_CRAWL_TICK,
    SUFFIX_OMNIMEMORY_DOCUMENT_CHANGED,
    SUFFIX_OMNIMEMORY_DOCUMENT_DISCOVERED,
    SUFFIX_OMNIMEMORY_DOCUMENT_INDEXED,
    SUFFIX_OMNIMEMORY_DOCUMENT_PARSE_FAILED,
    SUFFIX_OMNIMEMORY_DOCUMENT_REMOVED,
    SUFFIX_OMNIMEMORY_EXPIRE_MEMORY,
    SUFFIX_OMNIMEMORY_INTENT_QUERY_REQUESTED,
    SUFFIX_OMNIMEMORY_INTENT_QUERY_RESPONSE,
    SUFFIX_OMNIMEMORY_INTENT_STORE_FAILED,
    SUFFIX_OMNIMEMORY_INTENT_STORED,
    SUFFIX_OMNIMEMORY_LIFECYCLE_TRANSITION_FAILED,
    SUFFIX_OMNIMEMORY_MEMORY_ACCESSED,
    SUFFIX_OMNIMEMORY_MEMORY_ARCHIVE_INITIATED,
    SUFFIX_OMNIMEMORY_MEMORY_ARCHIVED,
    SUFFIX_OMNIMEMORY_MEMORY_DELETED,
    SUFFIX_OMNIMEMORY_MEMORY_EXPIRED,
    SUFFIX_OMNIMEMORY_MEMORY_RESTORED,
    SUFFIX_OMNIMEMORY_MEMORY_RETRIEVAL_REQUESTED,
    SUFFIX_OMNIMEMORY_MEMORY_RETRIEVAL_RESPONSE,
    SUFFIX_OMNIMEMORY_MEMORY_RETRIEVED,
    SUFFIX_OMNIMEMORY_MEMORY_STORED,
    SUFFIX_OMNIMEMORY_MEMORY_UPDATED,
    SUFFIX_OMNIMEMORY_RESTORE_MEMORY,
    SUFFIX_OMNIMEMORY_RUNTIME_TICK,
    SUFFIX_PLATFORM_DLQ_MESSAGE,
    SUFFIX_REGISTRATION_SNAPSHOTS,
    SUFFIX_REGISTRY_REQUEST_INTROSPECTION,
    SUFFIX_REQUEST_INTROSPECTION,
    SUFFIX_RESOLUTION_DECIDED,
    SUFFIX_RUNNER_HEALTH_SNAPSHOT,
    SUFFIX_RUNTIME_ERROR,
    SUFFIX_RUNTIME_TICK,
    SUFFIX_SERVICE_HEARTBEAT,
    SUFFIX_TOPIC_CATALOG_CHANGED,
    SUFFIX_TOPIC_CATALOG_QUERY,
    SUFFIX_TOPIC_CATALOG_RESPONSE,
    SUFFIX_VALIDATION_CROSS_REPO_RUN_COMPLETED,
    SUFFIX_VALIDATION_CROSS_REPO_RUN_STARTED,
    SUFFIX_VALIDATION_CROSS_REPO_VIOLATIONS_BATCH,
    SUFFIX_WIRING_HEALTH_SNAPSHOT,
)
from omnibase_infra.topics.topic_resolver import (
    BusDescriptorNotFoundError,
    TopicResolutionError,
    TopicResolver,
)

__all__: list[str] = [
    # Platform suffix constants
    "SUFFIX_NODE_REGISTRATION",
    "SUFFIX_NODE_REGISTRATION_ACCEPTED",
    "SUFFIX_NODE_INTROSPECTION",
    "SUFFIX_NODE_HEARTBEAT",
    "SUFFIX_SERVICE_HEARTBEAT",
    "SUFFIX_REQUEST_INTROSPECTION",
    "SUFFIX_FSM_STATE_TRANSITIONS",
    "SUFFIX_RUNTIME_TICK",
    "SUFFIX_REGISTRATION_SNAPSHOTS",
    "SUFFIX_REGISTRY_REQUEST_INTROSPECTION",
    "SUFFIX_CONTRACT_REGISTERED",
    "SUFFIX_CONTRACT_DEREGISTERED",
    "SUFFIX_NODE_REGISTRATION_ACCEPTED",
    "SUFFIX_NODE_REGISTRATION_ACKED",
    # Resolution event ledger (OMN-2895)
    "SUFFIX_RESOLUTION_DECIDED",
    # Topic catalog suffix constants
    "SUFFIX_TOPIC_CATALOG_QUERY",
    "SUFFIX_TOPIC_CATALOG_RESPONSE",
    "SUFFIX_TOPIC_CATALOG_CHANGED",
    # Intelligence domain suffix constants
    "SUFFIX_INTELLIGENCE_CLAUDE_HOOK_EVENT",
    "SUFFIX_INTELLIGENCE_SESSION_OUTCOME",
    "SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITION",
    "SUFFIX_INTELLIGENCE_INTENT_CLASSIFIED",
    "SUFFIX_INTELLIGENCE_LLM_CALL_COMPLETED",
    "SUFFIX_INTELLIGENCE_PATTERN_LEARNED",
    "SUFFIX_INTELLIGENCE_PATTERN_STORED",
    "SUFFIX_INTELLIGENCE_PATTERN_PROMOTED",
    "SUFFIX_INTELLIGENCE_PATTERN_LIFECYCLE_TRANSITIONED",
    "SUFFIX_INTELLIGENCE_PATTERN_DISCOVERED",
    # Decision recording topics (OMN-2943)
    "SUFFIX_INTELLIGENCE_DECISION_RECORDED_EVT",
    "SUFFIX_INTELLIGENCE_DECISION_RECORDED_CMD",
    # Routing decision CMD topic (OMN-4299)
    "SUFFIX_OMNIINTELLIGENCE_ROUTING_DECISION_CMD",
    # AST code extraction pipeline topics (OMN-5669)
    "SUFFIX_INTELLIGENCE_CODE_CRAWL_REQUESTED",
    "SUFFIX_INTELLIGENCE_CODE_FILE_DISCOVERED",
    "SUFFIX_INTELLIGENCE_CODE_ENTITIES_EXTRACTED",
    # Feature flag events (OMN-5575)
    "SUFFIX_FEATURE_FLAG_CHANGED",
    # OmniBase Infra domain suffix constants
    "SUFFIX_BASELINES_COMPUTED",
    "SUFFIX_CIRCUIT_BREAKER_STATE",
    "SUFFIX_GMAIL_ARCHIVE_PURGED",
    "SUFFIX_WIRING_HEALTH_SNAPSHOT",
    # Runner health monitoring (OMN-6075)
    "SUFFIX_RUNNER_HEALTH_SNAPSHOT",
    # Runtime health event pipeline (OMN-5529)
    "SUFFIX_CONSUMER_HEALTH",
    "SUFFIX_CONSUMER_RESTART_CMD",
    "SUFFIX_RUNTIME_ERROR",
    # DLQ aggregation topic (OMN-6136)
    "SUFFIX_PLATFORM_DLQ_MESSAGE",
    # OmniMemory domain suffix constants
    "SUFFIX_OMNIMEMORY_DOCUMENT_DISCOVERED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_CHANGED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_REMOVED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_INDEXED",
    "SUFFIX_OMNIMEMORY_DOCUMENT_PARSE_FAILED",
    "SUFFIX_OMNIMEMORY_CRAWL_TICK",
    "SUFFIX_OMNIMEMORY_CRAWL_REQUESTED",
    "SUFFIX_OMNIMEMORY_RUNTIME_TICK",
    "SUFFIX_OMNIMEMORY_INTENT_STORED",
    "SUFFIX_OMNIMEMORY_INTENT_STORE_FAILED",
    "SUFFIX_OMNIMEMORY_INTENT_QUERY_REQUESTED",
    "SUFFIX_OMNIMEMORY_INTENT_QUERY_RESPONSE",
    "SUFFIX_OMNIMEMORY_MEMORY_STORED",
    "SUFFIX_OMNIMEMORY_MEMORY_RETRIEVED",
    "SUFFIX_OMNIMEMORY_MEMORY_UPDATED",
    "SUFFIX_OMNIMEMORY_MEMORY_DELETED",
    "SUFFIX_OMNIMEMORY_MEMORY_ACCESSED",
    "SUFFIX_OMNIMEMORY_MEMORY_EXPIRED",
    "SUFFIX_OMNIMEMORY_MEMORY_ARCHIVED",
    "SUFFIX_OMNIMEMORY_MEMORY_ARCHIVE_INITIATED",
    "SUFFIX_OMNIMEMORY_MEMORY_RESTORED",
    "SUFFIX_OMNIMEMORY_LIFECYCLE_TRANSITION_FAILED",
    "SUFFIX_OMNIMEMORY_MEMORY_RETRIEVAL_REQUESTED",
    "SUFFIX_OMNIMEMORY_MEMORY_RETRIEVAL_RESPONSE",
    "SUFFIX_OMNIMEMORY_EXPIRE_MEMORY",
    "SUFFIX_OMNIMEMORY_ARCHIVE_MEMORY",
    "SUFFIX_OMNIMEMORY_RESTORE_MEMORY",
    # OmniClaude agent observability topic suffix constants (OMN-6066..OMN-6072, OMN-3343)
    "SUFFIX_OMNICLAUDE_AGENT_ACTIONS",
    "SUFFIX_OMNICLAUDE_AGENT_EXECUTION_LOGS",
    "SUFFIX_OMNICLAUDE_AGENT_STATUS",
    "SUFFIX_OMNICLAUDE_AGENT_TRANSFORMATION",
    "SUFFIX_OMNICLAUDE_DETECTION_FAILURE",
    "SUFFIX_OMNICLAUDE_PERFORMANCE_METRICS",
    "SUFFIX_OMNICLAUDE_ROUTING_DECISION",
    "SUFFIX_OMNICLAUDE_SKILL_COMPLETED",
    "SUFFIX_OMNICLAUDE_SKILL_STARTED",
    # OmniClaude observability DLQ suffix constants (OMN-2945)
    "SUFFIX_OMNICLAUDE_AGENT_ACTIONS_DLQ",
    "SUFFIX_OMNICLAUDE_AGENT_OBSERVABILITY_DLQ",
    # OmniClaude fix-transition trace topic (OMN-4572)
    "SUFFIX_OMNICLAUDE_AGENT_TRACE_FIX_TRANSITION",
    # OmniClaude context audit topic suffix constants (OMN-5240)
    "SUFFIX_OMNICLAUDE_AUDIT_DISPATCH_VALIDATED",
    "SUFFIX_OMNICLAUDE_AUDIT_SCOPE_VIOLATION",
    "SUFFIX_OMNICLAUDE_AUDIT_CONTEXT_BUDGET_EXCEEDED",
    "SUFFIX_OMNICLAUDE_AUDIT_RETURN_BOUNDED",
    "SUFFIX_OMNICLAUDE_AUDIT_COMPRESSION_TRIGGERED",
    "SUFFIX_OMNICLAUDE_CONTEXT_AUDIT_DLQ",
    "SUFFIX_OMNICLAUDE_SKILL_LIFECYCLE_DLQ",
    # Validation domain topic suffix constants (OMN-5050)
    "SUFFIX_VALIDATION_CROSS_REPO_RUN_STARTED",
    "SUFFIX_VALIDATION_CROSS_REPO_VIOLATIONS_BATCH",
    "SUFFIX_VALIDATION_CROSS_REPO_RUN_COMPLETED",
    # Aggregate collections
    "ALL_PLATFORM_SUFFIXES",
    "ALL_PLATFORM_TOPIC_SPECS",
    "ALL_INTELLIGENCE_TOPIC_SPECS",
    "ALL_OMNIBASE_INFRA_TOPIC_SPECS",
    "ALL_OMNICLAUDE_TOPIC_SPECS",
    "ALL_OMNIMEMORY_TOPIC_SPECS",
    "ALL_OMNIBASE_INFRA_TOPIC_SPECS",
    "ALL_VALIDATION_TOPIC_SPECS",
    "ALL_PROVISIONED_SUFFIXES",
    "ALL_PROVISIONED_TOPIC_SPECS",
    # Topic spec model
    "ModelTopicSpec",
    # Bus descriptor model (Phase 5 - OMN-2894)
    "ModelBusDescriptor",
    # Topic resolution
    "TopicResolver",
    "TopicResolutionError",
    "BusDescriptorNotFoundError",
]
